addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"              % "0.9.19")
addSbtPlugin("com.eed3si9n"          % "sbt-buildinfo"             % "0.10.0")
addSbtPlugin("com.github.cb372"      % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("com.thesamet"          % "sbt-protoc"                % "0.99.34")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"                % "6.5.0")
addSbtPlugin("org.scalameta"         % "sbt-mdoc"                  % "2.2.5")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"              % "2.4.2")
// Conflicts with scalaPB
// addSbtPlugin("org.wartremover"  % "sbt-wartremover"           % "2.4.10")
addSbtPlugin("net.virtual-void"      % "sbt-dependency-graph"      % "0.10.0-RC1")
